# Generated by Django 4.2.16 on 2024-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancers', '0002_alter_freelancer_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='specialty',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='technologies',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
