# Generated by Django 4.2.16 on 2024-10-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancers', '0003_freelancer_specialty_freelancer_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
    ]
