# Generated by Django 4.2.16 on 2024-10-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancers', '0004_freelancer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='email_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
