# Generated by Django 4.2.16 on 2024-10-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancers', '0005_freelancer_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='email_address',
            field=models.CharField(max_length=255),
        ),
    ]
