# Generated by Django 4.2.16 on 2024-10-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancers', '0006_alter_freelancer_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='password',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='hashed_password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='email_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
