# Generated by Django 4.2.16 on 2024-10-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancers', '0007_remove_freelancer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='email_address',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='hashed_password',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
