# Generated by Django 4.2.16 on 2024-10-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freelancers', '0008_alter_freelancer_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='email_address',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
