# Generated by Django 4.2.16 on 2024-10-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hirers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirer',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
    ]
