# Generated by Django 4.2.16 on 2024-10-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hirers', '0002_hirer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirer',
            name='email_address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
