# Generated by Django 4.2.16 on 2024-10-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hirers', '0003_hirer_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hirer',
            name='password',
        ),
        migrations.AddField(
            model_name='hirer',
            name='hashed_password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
