# Generated by Django 4.2.16 on 2024-10-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hirers', '0004_remove_hirer_password_hirer_hashed_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirer',
            name='email_address',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='hirer',
            name='hashed_password',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
