# Generated by Django 4.2.16 on 2024-10-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hirers', '0005_alter_hirer_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirer',
            name='email_address',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
